[package]
name = "biodivine-algo-smt-inference"
version = "0.1.0"
edition = "2024"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
# If anyone is iterating over a hash type, we want them to explicitly
# disable the warning to track possible sources of non-determinism.
iter_over_hash_type = "warn"
# Warn about dangerous unchecked integer conversions.
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_sign_loss = "warn"

[features]
default = ["z3-gh-release"]

# Faster build, but may not work on every platform (a pre-built Z3 release must be on GitHub).
z3-gh-release = ["z3/gh-release", "z3/num"]

# Slower build, but more robust (will build a fresh Z3 instance every time).
z3-vendored = ["z3/vendored", "z3/num"]

[dependencies]
macros = { path = "macros" }
biodivine-lib-param-bn = "0.7.2"
biodivine-lib-bdd = "0.6.3"
itertools = "0.14.0"
#z3 = "0.19.2"
z3 = { git = "https://github.com/sybila/z3.rs.git", rev = "3dc14105d4589c61d68f1fe6ce85b503e31ce290" }
num-rational = "0.4.2"
num-traits = "0.2.19"
csv = "1.4"
clap = { version = "4.5", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
downcast-rs = "2.0"
auto_impl = "1.3"
log = "0.4"
env_logger = "0.11"
linked_hash_set = "0.1"
big-rational-str = "0.1"
regex = "1.12.4"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"