use crate::bn_inference::constraints::check_state_exists;
use crate::bn_inference::{InferenceProblem, InferenceProblemEncoder};
use crate::smt_solver::typed_ast::TypedAst;
use crate::smt_solver::{AbstractSolver, extract_specific_function_applications};
use anyhow::anyhow;
use biodivine_algo_smt_inference::bn_inference::UpdateFunctionDefinition;
use biodivine_algo_smt_inference::bn_inference::constraints::check_variable_name_exists;
use biodivine_lib_param_bn::VariableId;
use linked_hash_set::LinkedHashSet;
use regex::Regex;
use std::collections::{BTreeMap, BTreeSet};
use std::str::FromStr;
use std::sync::LazyLock;
use z3::ast::Bool;
use z3::{Model, SatResult};

/// Matches `$name` to identify functions.
static RE_DOLLAR_NAME: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^\$([a-zA-Z_][a-zA-Z0-9_]*)$").unwrap());

/// Matches `name/name`, `*/name`, `name/*`, and `*/*` to identify `state/variable` combinations.
static RE_NAME_SLASH_NAME: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"^([a-zA-Z_][a-zA-Z0-9_]*|\*)/([a-zA-Z_][a-zA-Z0-9_]*|\*)$").unwrap()
});

/// Represents a single "object" that can be blocked during solution enumeration. When multiple
/// blocking atoms are defined, the enumerated solutions must differ in at least one atom.
#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum BlockingAtom {
    /// Blocks all variables valuations across all states (represented as `*/*`).
    AllStates,

    /// Block all variable valuations in the given state (represented as `state/*`).
    State(String),

    /// Block the valuations of the given variable across all states (represented as `*/variable`).
    Variable(String),

    /// Block the valuation of a single variable in a given state (represented as `state/variable`).
    VariableInState(String, String),

    /// Block the partial specification of an update function given by the points that
    /// appear in the inference constraints (represented as `$variable`).
    ///
    /// Note (1): This does not actually enumerate *all* admissible update functions, only those
    /// that are "observably different" in the context of the SMT query. To enumerate all
    /// functions, we need to also enumerate all functions admissible under the point-wise
    /// partial function specification.
    ///
    /// Note (2): If the function is fully specified, this should not generate any additional
    /// constraints and will simply repeat the same result until other options for the remaining
    /// blocking atoms are exhausted.
    FunctionPoints(String),
}

impl BlockingAtom {
    /// Check that the blocking atom can be safely applied in the given [`InferenceProblem`].
    pub fn validate<S: 'static>(&self, problem: &InferenceProblem<S>) -> Result<(), anyhow::Error> {
        match self {
            BlockingAtom::State(state_name) => check_state_exists(problem, state_name),
            BlockingAtom::Variable(var_name) | BlockingAtom::FunctionPoints(var_name) => {
                check_variable_name_exists(problem, var_name)?;
                Ok(())
            }
            BlockingAtom::VariableInState(state_name, var_name) => {
                check_state_exists(problem, state_name)?;
                check_variable_name_exists(problem, var_name)?;
                Ok(())
            }
            BlockingAtom::AllStates => Ok(()),
        }
    }
}

impl FromStr for BlockingAtom {
    type Err = anyhow::Error;

    fn from_str(input: &str) -> Result<Self, Self::Err> {
        if let Some(caps) = RE_DOLLAR_NAME.captures(input) {
            Ok(BlockingAtom::FunctionPoints(caps[1].to_string()))
        } else if let Some(caps) = RE_NAME_SLASH_NAME.captures(input) {
            let state_name = caps[1].to_string();
            let var_name = caps[2].to_string();
            match (state_name.as_str(), var_name.as_str()) {
                ("*", "*") => Ok(BlockingAtom::AllStates),
                ("*", _) => Ok(BlockingAtom::Variable(var_name)),
                (_, "*") => Ok(BlockingAtom::State(var_name)),
                (_, _) => Ok(BlockingAtom::VariableInState(state_name, var_name)),
            }
        } else {
            Err(anyhow!(
                "Input `{input}` is not an update function (`$name`) or a state expression (`state/variable`)"
            ))
        }
    }
}

/// Iterates through [`Model`] instances generated by an SMT solver such that each [`Model`]
/// represents a unique combination of values across given "blocking atoms".
///
/// These "blocking atoms" can correspond to state variables or point-wise update function
/// definitions (see [`BlockingAtom`]). The iterator also needs a reference to
/// [`InferenceProblemEncoder`] in order to generate blocking clauses from
/// individual [`BlockingAtom`] instances.
///
/// Note that the solver is permanently modified as additional blocking clauses are added
/// throughout iteration. Some solvers support "scopes" via `push` and `pop` commands.
/// These can be used to restore the solver state after iteration is complete, but this is
/// up to the user of [`InferenceProblemIterator`] to implement.
///
pub struct InferenceProblemIterator<'a, SOLVER: AbstractSolver + 'static> {
    encoder: &'a InferenceProblemEncoder<SOLVER>,
    solver: SOLVER,
    // Note: Some atoms can "overlap" (e.g., `*/*` and `x/*`). This introduces some repetition
    // into individual blocking clauses, but is ultimately harmless in terms of correctness.
    blocking_atoms: BTreeSet<BlockingAtom>,
    // Precomputed map of all unique function applications. This is used for blocking
    // functions (no need to search through all assertions on every iteration).
    unique_fn_applications: BTreeMap<VariableId, LinkedHashSet<TypedAst>>,
}

impl<'a, SOLVER: AbstractSolver + 'static> InferenceProblemIterator<'a, SOLVER> {
    pub fn new(
        encoder: &'a InferenceProblemEncoder<SOLVER>,
        solver: SOLVER,
        blocking_atoms: &[BlockingAtom],
    ) -> Result<Self, anyhow::Error> {
        // Check that all blocking atoms are valid.
        for atom in blocking_atoms {
            atom.validate(&encoder.problem)?;
        }

        // Collect metadata for function applications.
        let mut fn_applications = BTreeMap::new();
        for atom in blocking_atoms {
            if let BlockingAtom::FunctionPoints(var_name) = atom {
                let var_id = encoder
                    .problem
                    .find_variable(var_name)
                    .expect("Correctness violation: Variable does not exist.");
                if let UpdateFunctionDefinition::Uninterpreted(declaration) =
                    encoder.update_function(var_id)
                {
                    // Only uninterpreted functions need to be processed this way. Fully specified
                    // functions do not need to be blocked.

                    let mut applications = LinkedHashSet::new();
                    for assertion in solver.get_assertions() {
                        applications.extend(
                            extract_specific_function_applications(&assertion, declaration)
                                .into_iter()
                                .map(|it| {
                                    TypedAst::try_from(it)
                                        .expect("Correctness violation: Function has invalid type.")
                                }),
                        );
                    }

                    fn_applications.insert(var_id, applications);
                }
            }
        }

        Ok(InferenceProblemIterator {
            encoder,
            solver,
            blocking_atoms: BTreeSet::from_iter(blocking_atoms.iter().cloned()),
            unique_fn_applications: fn_applications,
        })
    }

    pub fn solver(&self) -> &SOLVER {
        &self.solver
    }

    pub fn into_solver(self) -> SOLVER {
        self.solver
    }

    /// Generate a [`Bool`] formula that is true in every model that shares the value of
    /// the given variable in the given state with the current [`Model`].
    fn block_state_variable_atom(&self, model: &Model, state: &str, variable: VariableId) -> Bool {
        let atom_ast = self.encoder.state_atom(state, variable);
        let atom_eval = atom_ast
            .eval_as_constant(model)
            .expect("Correctness violation: Cannot evaluate state value.");
        atom_ast
            .eq(&atom_ast.ast_type().new_value(atom_eval))
            .expect("Correctness violation: Atom and its evaluation are incomparable.")
    }

    /// Generate a [`Bool`] formula that is true in every model that shares the valuation
    /// of the given state with the given [`Model`].
    fn block_state_atoms(&self, model: &Model, state: &str) -> Bool {
        let args = self
            .encoder
            .problem
            .variables()
            .map(|var| self.block_state_variable_atom(model, state, var))
            .collect::<Vec<_>>();
        Bool::and(&args)
    }

    /// Generate a [`Bool`] formula that is true in every model that shares the valuation
    /// of a variable across all states with the given [`Model`].
    fn block_variable_atoms(&self, model: &Model, variable: VariableId) -> Bool {
        let args = self
            .encoder
            .problem
            .states()
            .map(|state| self.block_state_variable_atom(model, &state, variable))
            .collect::<Vec<_>>();
        Bool::and(&args)
    }

    /// Generate a [`Bool`] formula that is true in every model that shares the valuation
    /// of all states (across all variables) with the given [`Model`].
    fn block_all_state_atoms(&self, model: &Model) -> Bool {
        let args = self
            .encoder
            .problem
            .states()
            .map(|state| self.block_state_atoms(model, &state))
            .collect::<Vec<_>>();
        Bool::and(&args)
    }

    /// Generate a [`Bool`] formula that is true in every model that shares the same
    /// point-based partial specification of the update function corresponding
    /// to the given variable.
    fn block_function_points(&self, model: &Model, variable: VariableId) -> Bool {
        if let UpdateFunctionDefinition::Uninterpreted(_) = self.encoder.update_function(variable) {
            let points = self
                .unique_fn_applications
                .get(&variable)
                .expect("Correctness violation: Function points not found.");

            // Evaluate the function across all relevant points, but only keep unique values:
            let points: LinkedHashSet<(Vec<TypedAst>, TypedAst)> = points
                .iter()
                .map(|app| {
                    let args = app
                        .typed_children()
                        .expect("Correctness violation: Argument types invalid.")
                        .into_iter()
                        .map(|arg| {
                            arg.eval_in(model)
                                .expect("Correctness violation: Argument cannot be evaluated.")
                        })
                        .collect::<Vec<_>>();
                    let output = app
                        .eval_in(model)
                        .expect("Correctness violation: Function call cannot be evaluated.");
                    (args, output)
                })
                .collect::<LinkedHashSet<_>>();

            // Build an assertion for each unique point in the set:
            let point_assertions = points
                .into_iter()
                .map(|(args, output)| {
                    let application = self.encoder.mk_update_function_call(variable, &args);
                    application.eq(&output).expect(
                        "Correctness violation: Function output and application incompatible.",
                    )
                })
                .collect::<Vec<_>>();

            Bool::and(&point_assertions)
        } else {
            // A fully specified function cannot be blocked, because there are no
            // other solutions to explore (all other models will share this solution).
            Bool::from_bool(true)
        }
    }

    /// A utility function that retrieves a [`VariableId`] based on a given variable name.
    /// The function panics if the name does not exist. Generally, this method should be called
    /// only once validation has passed and the names are guaranteed to represent valid variables.
    fn get_variable(&self, name: &str) -> VariableId {
        self.encoder
            .problem
            .find_variable(name)
            .expect("Correctness violation: Variable does not exist.")
    }
}

impl<'a, SOLVER: AbstractSolver + 'static> Iterator for InferenceProblemIterator<'a, SOLVER> {
    type Item = Model;

    fn next(&mut self) -> Option<Self::Item> {
        match self.solver.check() {
            SatResult::Unsat => return None,
            // Result can be unknown if the solving was interrupted via an OS signal.
            SatResult::Unknown => return None,
            SatResult::Sat => {}
        }

        let model = self
            .solver
            .get_model()
            .expect("Correctness violation: Solver is SAT but has no model.");

        let mut blocking_clauses = Vec::new();

        for block in &self.blocking_atoms {
            let clause = match block {
                BlockingAtom::AllStates => self.block_all_state_atoms(&model),
                BlockingAtom::State(state_name) => self.block_state_atoms(&model, state_name),
                BlockingAtom::Variable(var_name) => {
                    self.block_variable_atoms(&model, self.get_variable(var_name))
                }
                BlockingAtom::VariableInState(state_name, var_name) => {
                    self.block_state_variable_atom(&model, state_name, self.get_variable(var_name))
                }
                BlockingAtom::FunctionPoints(var_name) => {
                    self.block_function_points(&model, self.get_variable(var_name))
                }
            };
            blocking_clauses.push(clause);
        }

        // Describes the exact values of blocked elements in the current `model`.
        let blocking_formula = Bool::and(&blocking_clauses);
        // Prevents future models from having the same values.
        self.solver.assert(&blocking_formula.not());

        Some(model)
    }
}
